

{
  'fpl_url' : 'https://fantasy.premierleague.com/api/bootstrap-static/',
  'team_url' : 'https://fantasy.premierleague.com/api/entry/team_id/event/game_week/picks/',
  'base':  'https://fantasy.premierleague.com/api/entry/',
  'gameweek': '10/picks/',
  'team_id' : '296501/event/'
}
